export const TOPICS = [
  { id: 'javascript', label: 'JavaScript' },
  { id: 'html', label: 'HTML' },
  { id: 'css', label: 'CSS' },
  { id: 'react', label: 'React' },
  { id: 'redux', label: 'Redux' },
]

export const QUESTIONS = [
  // JavaScript (20)
  { id: 'js-1',  topic: 'javascript', difficulty: 'easy',   text: 'What is a closure in JavaScript? Explain with an example.' },
  { id: 'js-2',  topic: 'javascript', difficulty: 'medium', text: 'What is the difference between var, let, and const?' },
  { id: 'js-3',  topic: 'javascript', difficulty: 'medium', text: 'Explain the event loop and how asynchronous code works in JavaScript.' },
  { id: 'js-4',  topic: 'javascript', difficulty: 'medium', text: 'What are Promises? How do they differ from callbacks?' },
  { id: 'js-5',  topic: 'javascript', difficulty: 'medium', text: 'What is async/await and how does it relate to Promises?' },
  { id: 'js-6',  topic: 'javascript', difficulty: 'easy',   text: 'What is hoisting in JavaScript?' },
  { id: 'js-7',  topic: 'javascript', difficulty: 'medium', text: 'Explain prototypal inheritance in JavaScript.' },
  { id: 'js-8',  topic: 'javascript', difficulty: 'easy',   text: 'What is the difference between == and === in JavaScript?' },
  { id: 'js-9',  topic: 'javascript', difficulty: 'medium', text: 'What is the "this" keyword and how does its value get determined?' },
  { id: 'js-10', topic: 'javascript', difficulty: 'medium', text: 'What are arrow functions and how do they differ from regular functions?' },
  { id: 'js-11', topic: 'javascript', difficulty: 'hard',   text: 'What is debouncing and throttling? When would you use each?' },
  { id: 'js-12', topic: 'javascript', difficulty: 'medium', text: 'Explain the difference between null and undefined.' },
  { id: 'js-13', topic: 'javascript', difficulty: 'medium', text: 'What are higher-order functions? Give examples.' },
  { id: 'js-14', topic: 'javascript', difficulty: 'hard',   text: 'What is the difference between call, apply, and bind?' },
  { id: 'js-15', topic: 'javascript', difficulty: 'medium', text: 'What is event delegation and why is it useful?' },
  { id: 'js-16', topic: 'javascript', difficulty: 'hard',   text: 'What is a WeakMap and WeakSet? How do they differ from Map and Set?' },
  { id: 'js-17', topic: 'javascript', difficulty: 'medium', text: 'What is destructuring in JavaScript? Give examples of object and array destructuring.' },
  { id: 'js-18', topic: 'javascript', difficulty: 'medium', text: 'What are generators and iterators in JavaScript?' },
  { id: 'js-19', topic: 'javascript', difficulty: 'hard',   text: 'Explain the concept of memoization and implement a simple version.' },
  { id: 'js-20', topic: 'javascript', difficulty: 'medium', text: 'What is the difference between deep copy and shallow copy?' },

  // HTML (20)
  { id: 'html-1',  topic: 'html', difficulty: 'easy',   text: 'What is the difference between HTML and HTML5?' },
  { id: 'html-2',  topic: 'html', difficulty: 'easy',   text: 'What are semantic HTML elements? Give examples and why they matter.' },
  { id: 'html-3',  topic: 'html', difficulty: 'easy',   text: 'What is the difference between <div> and <span>?' },
  { id: 'html-4',  topic: 'html', difficulty: 'medium', text: 'What are data attributes in HTML and when would you use them?' },
  { id: 'html-5',  topic: 'html', difficulty: 'easy',   text: 'Explain the difference between <script>, <script async>, and <script defer>.' },
  { id: 'html-6',  topic: 'html', difficulty: 'medium', text: 'What is the purpose of the meta viewport tag?' },
  { id: 'html-7',  topic: 'html', difficulty: 'easy',   text: 'What is the difference between cookies, localStorage, and sessionStorage?' },
  { id: 'html-8',  topic: 'html', difficulty: 'medium', text: 'What are web workers and what problem do they solve?' },
  { id: 'html-9',  topic: 'html', difficulty: 'easy',   text: 'What is the purpose of the DOCTYPE declaration?' },
  { id: 'html-10', topic: 'html', difficulty: 'medium', text: 'How does the HTML form validation work? What are some built-in validation attributes?' },
  { id: 'html-11', topic: 'html', difficulty: 'medium', text: 'What is ARIA and why is it important for accessibility?' },
  { id: 'html-12', topic: 'html', difficulty: 'easy',   text: 'What is the difference between <link> and @import for stylesheets?' },
  { id: 'html-13', topic: 'html', difficulty: 'medium', text: 'What are iframes and what are their security concerns?' },
  { id: 'html-14', topic: 'html', difficulty: 'medium', text: 'Explain how the browser renders an HTML page (critical rendering path).' },
  { id: 'html-15', topic: 'html', difficulty: 'easy',   text: 'What is the difference between GET and POST HTTP methods?' },
  { id: 'html-16', topic: 'html', difficulty: 'medium', text: 'What is Cross-Site Scripting (XSS) and how can you prevent it in HTML?' },
  { id: 'html-17', topic: 'html', difficulty: 'easy',   text: 'What are void elements in HTML? Give 5 examples.' },
  { id: 'html-18', topic: 'html', difficulty: 'medium', text: 'How do you make a website accessible to screen readers?' },
  { id: 'html-19', topic: 'html', difficulty: 'medium', text: 'What is the difference between the <canvas> and <svg> elements?' },
  { id: 'html-20', topic: 'html', difficulty: 'hard',   text: 'What are Service Workers and how do they enable Progressive Web Apps?' },

  // CSS (20)
  { id: 'css-1',  topic: 'css', difficulty: 'easy',   text: 'What is the CSS box model? Explain content, padding, border, and margin.' },
  { id: 'css-2',  topic: 'css', difficulty: 'easy',   text: 'What is the difference between display: block, inline, and inline-block?' },
  { id: 'css-3',  topic: 'css', difficulty: 'medium', text: 'Explain CSS Flexbox. What are the main properties?' },
  { id: 'css-4',  topic: 'css', difficulty: 'medium', text: 'Explain CSS Grid. How does it differ from Flexbox?' },
  { id: 'css-5',  topic: 'css', difficulty: 'medium', text: 'What is CSS specificity and how is it calculated?' },
  { id: 'css-6',  topic: 'css', difficulty: 'easy',   text: 'What is the difference between position: relative, absolute, fixed, and sticky?' },
  { id: 'css-7',  topic: 'css', difficulty: 'medium', text: 'What are CSS custom properties (variables)? How are they used?' },
  { id: 'css-8',  topic: 'css', difficulty: 'medium', text: 'What are CSS pseudo-classes and pseudo-elements? Give examples.' },
  { id: 'css-9',  topic: 'css', difficulty: 'easy',   text: 'How do CSS media queries work? Give an example.' },
  { id: 'css-10', topic: 'css', difficulty: 'medium', text: 'What is the difference between em, rem, px, vh, and vw units?' },
  { id: 'css-11', topic: 'css', difficulty: 'medium', text: 'What is BEM methodology and why is it used?' },
  { id: 'css-12', topic: 'css', difficulty: 'hard',   text: 'What is CSS-in-JS? What are the trade-offs compared to traditional CSS?' },
  { id: 'css-13', topic: 'css', difficulty: 'medium', text: 'Explain the z-index property and stacking context.' },
  { id: 'css-14', topic: 'css', difficulty: 'easy',   text: 'What are CSS transitions and animations? When would you use each?' },
  { id: 'css-15', topic: 'css', difficulty: 'medium', text: 'What is the difference between visibility: hidden and display: none?' },
  { id: 'css-16', topic: 'css', difficulty: 'medium', text: 'What is CSS specificity and how do you resolve specificity conflicts?' },
  { id: 'css-17', topic: 'css', difficulty: 'hard',   text: 'Explain CSS containment and the content-visibility property for performance.' },
  { id: 'css-18', topic: 'css', difficulty: 'easy',   text: 'How do you center an element horizontally and vertically in CSS?' },
  { id: 'css-19', topic: 'css', difficulty: 'medium', text: 'What is the cascade in CSS? How does it determine which styles apply?' },
  { id: 'css-20', topic: 'css', difficulty: 'hard',   text: 'What are CSS logical properties and why are they useful for internationalization?' },

  // React (20)
  { id: 'react-1',  topic: 'react', difficulty: 'easy',   text: 'What is the virtual DOM and how does React use it?' },
  { id: 'react-2',  topic: 'react', difficulty: 'easy',   text: 'What are React hooks? Explain useState and useEffect.' },
  { id: 'react-3',  topic: 'react', difficulty: 'medium', text: 'What is the difference between controlled and uncontrolled components?' },
  { id: 'react-4',  topic: 'react', difficulty: 'medium', text: 'What is the React component lifecycle? How does it map to hooks?' },
  { id: 'react-5',  topic: 'react', difficulty: 'medium', text: 'Explain React Context API. When would you use it instead of Redux?' },
  { id: 'react-6',  topic: 'react', difficulty: 'medium', text: 'What is useMemo and useCallback? When should you use them?' },
  { id: 'react-7',  topic: 'react', difficulty: 'easy',   text: 'What are React keys and why are they important in lists?' },
  { id: 'react-8',  topic: 'react', difficulty: 'medium', text: 'What is code splitting and lazy loading in React?' },
  { id: 'react-9',  topic: 'react', difficulty: 'medium', text: 'What are React error boundaries and how do they work?' },
  { id: 'react-10', topic: 'react', difficulty: 'hard',   text: 'Explain React reconciliation and the diffing algorithm.' },
  { id: 'react-11', topic: 'react', difficulty: 'medium', text: 'What is the useReducer hook and when would you prefer it over useState?' },
  { id: 'react-12', topic: 'react', difficulty: 'medium', text: 'What are custom hooks? Create a simple useFetch hook.' },
  { id: 'react-13', topic: 'react', difficulty: 'hard',   text: 'What is React Concurrent Mode and what problems does it solve?' },
  { id: 'react-14', topic: 'react', difficulty: 'medium', text: 'What are render props and HOCs? How do hooks replace them?' },
  { id: 'react-15', topic: 'react', difficulty: 'easy',   text: 'What is the difference between state and props in React?' },
  { id: 'react-16', topic: 'react', difficulty: 'medium', text: 'What is React.memo and when should you use it?' },
  { id: 'react-17', topic: 'react', difficulty: 'hard',   text: 'How does React handle batching of state updates?' },
  { id: 'react-18', topic: 'react', difficulty: 'medium', text: 'What is the useRef hook? Give examples beyond just DOM refs.' },
  { id: 'react-19', topic: 'react', difficulty: 'medium', text: 'How would you optimize a React app that is rendering too slowly?' },
  { id: 'react-20', topic: 'react', difficulty: 'hard',   text: 'What is React Server Components and how does it differ from SSR?' },

  // Redux (20)
  { id: 'redux-1',  topic: 'redux', difficulty: 'easy',   text: 'What is Redux and what problem does it solve?' },
  { id: 'redux-2',  topic: 'redux', difficulty: 'easy',   text: 'Explain the three core principles of Redux.' },
  { id: 'redux-3',  topic: 'redux', difficulty: 'easy',   text: 'What is a Redux action and what must it contain?' },
  { id: 'redux-4',  topic: 'redux', difficulty: 'easy',   text: 'What is a reducer? What are the rules a reducer must follow?' },
  { id: 'redux-5',  topic: 'redux', difficulty: 'medium', text: 'What is the Redux store and how do you create one?' },
  { id: 'redux-6',  topic: 'redux', difficulty: 'medium', text: 'What is Redux middleware? Name two common examples.' },
  { id: 'redux-7',  topic: 'redux', difficulty: 'medium', text: 'What is Redux Thunk and how does it handle async actions?' },
  { id: 'redux-8',  topic: 'redux', difficulty: 'medium', text: 'What is Redux Saga and how does it differ from Thunk?' },
  { id: 'redux-9',  topic: 'redux', difficulty: 'medium', text: 'What is the useSelector and useDispatch hook from React-Redux?' },
  { id: 'redux-10', topic: 'redux', difficulty: 'medium', text: 'What is Redux Toolkit and what problems does it solve over plain Redux?' },
  { id: 'redux-11', topic: 'redux', difficulty: 'medium', text: 'What is createSlice in Redux Toolkit and what does it generate?' },
  { id: 'redux-12', topic: 'redux', difficulty: 'medium', text: 'What is the Immer library and how does Redux Toolkit use it?' },
  { id: 'redux-13', topic: 'redux', difficulty: 'hard',   text: 'What is RTK Query and how does it simplify data fetching in Redux apps?' },
  { id: 'redux-14', topic: 'redux', difficulty: 'medium', text: 'How do you handle side effects in Redux?' },
  { id: 'redux-15', topic: 'redux', difficulty: 'medium', text: 'What is the connect() function in React-Redux and when would you use it over hooks?' },
  { id: 'redux-16', topic: 'redux', difficulty: 'hard',   text: 'How would you structure a Redux store for a large-scale application?' },
  { id: 'redux-17', topic: 'redux', difficulty: 'medium', text: 'What is selector memoization and how does reselect help?' },
  { id: 'redux-18', topic: 'redux', difficulty: 'hard',   text: 'When would you choose Redux over React Context + useReducer?' },
  { id: 'redux-19', topic: 'redux', difficulty: 'medium', text: 'How do you handle optimistic updates in Redux?' },
  { id: 'redux-20', topic: 'redux', difficulty: 'hard',   text: 'How would you implement undo/redo functionality in Redux?' },
]

export function getQuestionsByTopic(topic) {
  return QUESTIONS.filter(q => q.topic === topic)
}
